from .local_customer import LocalCustomer
from .remote_customer import RemoteCustomer
from .cook import Cook
from .waiter import Waiter
from .administrator import Administrator
from .courier import Courier
from .order import Order
from .menu import Menu
from .dish import Dish
from .internet_service import InternetService
